- name: Install Vaultwarden
  hosts: vault.lab.internal
  remote_user: root
  tasks:
    - name: Add Docker-Repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: "0644"

    - name: Install Docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        state: present

    - name: activate and start Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Create Dir for Vaultwarden
      ansible.builtin.file:
        path: /opt/vaultwarden
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy Compose file for Docker
      ansible.builtin.copy:
        src: files/docker-compose.yml
        dest: /opt/vaultwarden/docker-compose.yml
        owner: root
        group: root
        mode: "0644"

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: vaultwarden
      register: output

